# .github/workflows/greetings.yml
name: Greet New Contributors

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions: read-all

jobs:
  greet:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@302b15743b1c67d603a110303e8785edce498666 # v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # The action automatically looks for .github/greetings.yml
